use crate::{distribution::dist_index_from_genotype, genotype::Genotype};
use serde::Serialize;

#[derive(Debug, Eq, PartialEq, Hash, Copy, Clone, Serialize)]
pub enum FlowerType {
    Rose,
    Cosmo,
    Lily,
    Pansy,
    Tulip,
    Hyacinth,
    Mum,
    Windflower,
}

#[derive(Debug, Eq, PartialEq, Hash, Copy, Clone, Serialize)]
pub enum FlowerColor {
    White,
    Yellow,
    Red,
    Purple,
    Pink,
    Orange,
    Black,
    Blue,
    Green,
}

pub const ROSES_LIST: [FlowerColor; 81] = {
    [
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::Purple,
        FlowerColor::Purple,
        FlowerColor::Purple,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::Purple,
        FlowerColor::Purple,
        FlowerColor::Purple,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::Red,
        FlowerColor::Pink,
        FlowerColor::White,
        FlowerColor::Red,
        FlowerColor::Pink,
        FlowerColor::White,
        FlowerColor::Red,
        FlowerColor::Pink,
        FlowerColor::Purple,
        FlowerColor::Orange,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Red,
        FlowerColor::Pink,
        FlowerColor::White,
        FlowerColor::Red,
        FlowerColor::Pink,
        FlowerColor::Purple,
        FlowerColor::Orange,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Orange,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Red,
        FlowerColor::Pink,
        FlowerColor::White,
        FlowerColor::Black,
        FlowerColor::Red,
        FlowerColor::Pink,
        FlowerColor::Black,
        FlowerColor::Red,
        FlowerColor::Pink,
        FlowerColor::Black,
        FlowerColor::Red,
        FlowerColor::Pink,
        FlowerColor::Orange,
        FlowerColor::Orange,
        FlowerColor::Yellow,
        FlowerColor::Red,
        FlowerColor::Red,
        FlowerColor::White,
        FlowerColor::Black,
        FlowerColor::Red,
        FlowerColor::Purple,
        FlowerColor::Orange,
        FlowerColor::Orange,
        FlowerColor::Yellow,
        FlowerColor::Orange,
        FlowerColor::Orange,
        FlowerColor::Yellow,
        FlowerColor::Blue,
        FlowerColor::Red,
        FlowerColor::White,
    ]
};

pub const COSMOS_LIST: [FlowerColor; 27] = { 
    [
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::White,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Pink,
        FlowerColor::Pink,
        FlowerColor::Pink,
        FlowerColor::Orange,
        FlowerColor::Orange,
        FlowerColor::Pink,
        FlowerColor::Orange,
        FlowerColor::Orange,
        FlowerColor::Orange,
        FlowerColor::Red,
        FlowerColor::Red,
        FlowerColor::Red,
        FlowerColor::Orange,
        FlowerColor::Orange,
        FlowerColor::Red,
        FlowerColor::Black,
        FlowerColor::Black,
        FlowerColor::Red,
    ]
};

pub const LILIES_LIST: [FlowerColor; 27] = { 
    [
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::Yellow,
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::White,
        FlowerColor::Red,
        FlowerColor::Pink,
        FlowerColor::White,
        FlowerColor::Orange,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Orange,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Black,
        FlowerColor::Red,
        FlowerColor::Pink,
        FlowerColor::Black,
        FlowerColor::Red,
        FlowerColor::Pink,
        FlowerColor::Orange,
        FlowerColor::Orange,
        FlowerColor::White,
    ]
};

pub const PANSIES_LIST: [FlowerColor; 27] = { 
    [
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::Blue,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Blue,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Red,
        FlowerColor::Red,
        FlowerColor::Blue,
        FlowerColor::Orange,
        FlowerColor::Orange,
        FlowerColor::Orange,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Red,
        FlowerColor::Red,
        FlowerColor::Purple,
        FlowerColor::Red,
        FlowerColor::Red,
        FlowerColor::Purple,
        FlowerColor::Orange,
        FlowerColor::Orange,
        FlowerColor::Purple,
    ]
};

pub const HYACINTHS_LIST: [FlowerColor; 27] = { 
    [
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::Blue,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::White,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Red,
        FlowerColor::Pink,
        FlowerColor::White,
        FlowerColor::Orange,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Orange,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Red,
        FlowerColor::Red,
        FlowerColor::Red,
        FlowerColor::Blue,
        FlowerColor::Red,
        FlowerColor::Red,
        FlowerColor::Purple,
        FlowerColor::Purple,
        FlowerColor::Purple,
    ]
};

pub const TULIPS_LIST: [FlowerColor; 27] = { 
    [
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::White,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Red,
        FlowerColor::Pink,
        FlowerColor::White,
        FlowerColor::Orange,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Orange,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Black,
        FlowerColor::Red,
        FlowerColor::Red,
        FlowerColor::Black,
        FlowerColor::Red,
        FlowerColor::Red,
        FlowerColor::Purple,
        FlowerColor::Purple,
        FlowerColor::Purple,
    ]
};

pub const MUMS_LIST: [FlowerColor; 27] = { 
    [
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::Purple,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::White,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Yellow,
        FlowerColor::Pink,
        FlowerColor::Pink,
        FlowerColor::Pink,
        FlowerColor::Yellow,
        FlowerColor::Red,
        FlowerColor::Pink,
        FlowerColor::Purple,
        FlowerColor::Purple,
        FlowerColor::Purple,
        FlowerColor::Red,
        FlowerColor::Red,
        FlowerColor::Red,
        FlowerColor::Purple,
        FlowerColor::Purple,
        FlowerColor::Red,
        FlowerColor::Green,
        FlowerColor::Green,
        FlowerColor::Red,
    ]
};

pub const WINDFLOWERS_LIST: [FlowerColor; 27] = { 
    [
        FlowerColor::White,
        FlowerColor::White,
        FlowerColor::Blue,
        FlowerColor::Orange,
        FlowerColor::Orange,
        FlowerColor::Blue,
        FlowerColor::Orange,
        FlowerColor::Orange,
        FlowerColor::Orange,
        FlowerColor::Red,
        FlowerColor::Red,
        FlowerColor::Blue,
        FlowerColor::Pink,
        FlowerColor::Pink,
        FlowerColor::Pink,
        FlowerColor::Orange,
        FlowerColor::Orange,
        FlowerColor::Orange,
        FlowerColor::Red,
        FlowerColor::Red,
        FlowerColor::Purple,
        FlowerColor::Red,
        FlowerColor::Red,
        FlowerColor::Purple,
        FlowerColor::Pink,
        FlowerColor::Pink,
        FlowerColor::Purple,
    ]
};

pub fn get_color(flower_type: &FlowerType, genotype: Genotype) -> FlowerColor {
    let index = dist_index_from_genotype(genotype);
    match flower_type {
        FlowerType::Rose => ROSES_LIST[index],
        FlowerType::Cosmo => COSMOS_LIST[index],
        FlowerType::Lily => LILIES_LIST[index],
        FlowerType::Pansy => PANSIES_LIST[index],
        FlowerType::Tulip => TULIPS_LIST[index],
        FlowerType::Hyacinth => HYACINTHS_LIST[index],
        FlowerType::Mum => MUMS_LIST[index],
        FlowerType::Windflower => WINDFLOWERS_LIST[index],
    }
}